name: "issue"
description: "issue form"
# title 필드에 기본 제목을 지정 (빈 문자열이 아님)
title: "[이슈] 제목을 입력해주세요"
labels: []
assignees:
  - ienrum
body:
  - type: textarea
    id: issue_content
    attributes:
      label: "이슈 내용"
      description: "추가하려는 기능에 대해 간결하게 설명해주세요"

  - type: input
    id: issue_summary
    attributes:
      label: "이슈 요약"
      description: "이슈의 주요 내용을 간략하게 요약해주세요"
      placeholder: "예: 사용자 로그인 기능 개선"
